// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38WD-cQY-1t0rVd60YMt8lOVm0xvccIA',
    appId: '1:86677154556:web:e88767dda0b4a829bd0579',
    messagingSenderId: '86677154556',
    projectId: 'moneymate-ee745',
    authDomain: 'moneymate-ee745.firebaseapp.com',
    storageBucket: 'moneymate-ee745.firebasestorage.app',
    measurementId: 'G-P5T49P1HLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9Ebn9WeTECYpn-E8fGN4mzQZNCDxQug',
    appId: '1:86677154556:android:216e508b74fabb93bd0579',
    messagingSenderId: '86677154556',
    projectId: 'moneymate-ee745',
    storageBucket: 'moneymate-ee745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVXc50cu1xqkT8wifu7A_nSyHiOl5CsQ',
    appId: '1:86677154556:ios:1b5d599880e80f58bd0579',
    messagingSenderId: '86677154556',
    projectId: 'moneymate-ee745',
    storageBucket: 'moneymate-ee745.firebasestorage.app',
    iosBundleId: 'com.example.moneymateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVXc50cu1xqkT8wifu7A_nSyHiOl5CsQ',
    appId: '1:86677154556:ios:1b5d599880e80f58bd0579',
    messagingSenderId: '86677154556',
    projectId: 'moneymate-ee745',
    storageBucket: 'moneymate-ee745.firebasestorage.app',
    iosBundleId: 'com.example.moneymateapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38WD-cQY-1t0rVd60YMt8lOVm0xvccIA',
    appId: '1:86677154556:web:9bb43b99a9235c3cbd0579',
    messagingSenderId: '86677154556',
    projectId: 'moneymate-ee745',
    authDomain: 'moneymate-ee745.firebaseapp.com',
    storageBucket: 'moneymate-ee745.firebasestorage.app',
    measurementId: 'G-3BD7DS3GN6',
  );
}
